### ISSUE TITLE
RSS::NotAvailableValueError, string length (265) exceeds the limit 128 (ArgumentError)

### ISSUE THREAD

**Issue by husita-h** [husita-h/rss_feed_builder#2]
### RSS::NotAvailableValueError

エラー
```
/usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:85:in `rescue in pubDate=': value <11:25更新> of tag <pubDate> is not available. (RSS::NotAvailableValueError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:82:in `pubDate='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/dublincore.rb:43:in `date='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:243:in `block in setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:261:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:252:in `block in to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:45:in `setup_items'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:33:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:415:in `setup_channel'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:22:in `setup_elements'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:446:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:440:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
        from /app/lib/feeds/builder.rb:28:in `build_xml'
        from /app/lib/feeds/builder.rb:6:in `call'
        from /app/lib/publish.rb:29:in `build_xml'
        from /app/lib/publish.rb:15:in `execute'
        from lib/main.rb:3:in `<main>'
/usr/local/lib/ruby/3.1.0/time.rb:542:in `rfc2822': not RFC 2822 compliant date: #<Nokogiri::XML::Text:0x280 "11:25更新"> (ArgumentError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:83:in `pubDate='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/dublincore.rb:43:in `date='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:243:in `block in setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:261:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:252:in `block in to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:45:in `setup_items'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:33:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:415:in `setup_channel'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:22:in `setup_elements'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:446:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:440:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
        from /app/lib/feeds/builder.rb:28:in `build_xml'
        from /app/lib/feeds/builder.rb:6:in `call'
        from /app/lib/publish.rb:29:in `build_xml'
        from /app/lib/publish.rb:15:in `execute'
        from lib/main.rb:3:in `<main>'
```

**Comment by husita-h** [comment]
```
/usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:85:in `rescue in pubDate=': value <内田　利男氏（うちだ・としお＝元県視力障害者福祉連合会＜現県視覚障害者福祉会＞会長）17日午前9時24分、病気のため青森市の病院で死去、88歳。群馬県桐生市出身。自宅は青森市平新田森越15の20。…> of tag <pubDate> is not available. (RSS::NotAvailableValueError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:82:in `pubDate='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/dublincore.rb:43:in `date='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:243:in `block in setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:261:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:252:in `block in to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:45:in `setup_items'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:33:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:415:in `setup_channel'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:22:in `setup_elements'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:446:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:440:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
        from /app/lib/feeds/builder.rb:28:in `build_xml'
        from /app/lib/feeds/builder.rb:6:in `call'
        from /app/lib/publish.rb:29:in `build_xml'
        from /app/lib/publish.rb:15:in `execute'
        from lib/main.rb:3:in `<main>'
/usr/local/lib/ruby/3.1.0/time.rb:542:in `rfc2822': not RFC 2822 compliant date: #<Nokogiri::XML::Text:0x280 "内田　利男氏（うちだ・としお＝元県視力障害者福祉連合会＜現県視覚障害者福祉会＞会長）17日午前9時24分、病気のため青森市の病院で死去、88歳。群馬県桐生市出身。自宅は青森市平新田森越15の20。…"> (ArgumentError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/2.0.rb:83:in `pubDate='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/dublincore.rb:43:in `date='
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:243:in `block in setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:238:in `setup_values'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:261:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:252:in `block in to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:251:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:45:in `setup_items'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:33:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:415:in `setup_channel'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/0.9.rb:22:in `setup_elements'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:446:in `to_feed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:440:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
        from /app/lib/feeds/builder.rb:28:in `build_xml'
        from /app/lib/feeds/builder.rb:6:in `call'
        from /app/lib/publish.rb:29:in `build_xml'
        from /app/lib/publish.rb:15:in `execute'
        from lib/main.rb:3:in `<main>'
```

**Comment by husita-h** [comment]
### _parse': string length (265) exceeds the limit 128 (ArgumentError)

```
/usr/local/lib/ruby/3.1.0/time.rb:380:in `_parse': string length (265) exceeds the limit 128 (ArgumentError)
        from /usr/local/lib/ruby/3.1.0/time.rb:380:in `parse'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:376:in `_parse_date_if_needed'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:735:in `date='
        from /app/lib/feeds/builder.rb:43:in `block (3 levels) in build_xml'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:58:in `new_item'
        from /app/lib/feeds/builder.rb:40:in `block (2 levels) in build_xml'
        from /app/lib/feeds/builder.rb:37:in `each'
        from /app/lib/feeds/builder.rb:37:in `each_with_index'
        from /app/lib/feeds/builder.rb:37:in `block in build_xml'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
        from /usr/local/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
        from /app/lib/feeds/builder.rb:28:in `build_xml'
        from /app/lib/feeds/builder.rb:6:in `call'
        from /app/lib/publish.rb:29:in `build_xml'
        from /app/lib/publish.rb:11:in `initialize'
        from lib/main.rb:3:in `new'
        from lib/main.rb:3:in `<main>'
```

**Comment by husita-h** [comment]
上の問題もあるが、
>{:path=>"/articles/-/1457754",
 :title=>"21:44更新",
 :date=>
  "J3で今季18チーム中10位に終わったヴァンラーレ八戸の下平賢吾社長とMF新井山祥智（37）＝五戸町出身＝が20日、青森市の東奥日報社を訪れた。下平社長はJ初の通算700試合指揮を達成した石崎信弘…"}

titleとdateも反対だった。
